# Generated by Django 4.0 on 2021-12-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='youtubeVideo',
            fields=[
                ('videoId', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('videoTitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publishDatetime', models.DateTimeField()),
                ('thumbnailURL', models.URLField()),
            ],
            options={
                'ordering': ['-publishDatetime'],
                'get_latest_by': 'publishDatetime',
            },
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['videoId'], name='api_youtube_videoId_27a52a_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['publishDatetime'], name='api_youtube_publish_b0ca06_idx'),
        ),
    ]
